/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author sxnti
 */
public class CambiarDivisa extends javax.swing.JFrame {

    /**
     * Creates new form CambiarDivisa
     */
    public CambiarDivisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TipoDeDivisa = new javax.swing.JComboBox<>();
        Saldo1 = new javax.swing.JLabel();
        Saldo2 = new javax.swing.JLabel();
        Saldo3 = new javax.swing.JLabel();
        MontoACambiar = new javax.swing.JTextField();
        Saldo4 = new javax.swing.JLabel();
        MontoCambiado = new javax.swing.JTextField();
        simular_cambio = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        Saldo5 = new javax.swing.JLabel();
        TipoDeDenom = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        tvcomision = new javax.swing.JTextField();
        ConfirmarCambio1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 111, 149));

        TipoDeDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar estadounidense", "Real Brasileño", "Libra Esterlina", "Euro", "Dirham" }));
        TipoDeDivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeDivisaActionPerformed(evt);
            }
        });

        Saldo1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        Saldo1.setText("Cambio de Divisas");
        Saldo1.setPreferredSize(new java.awt.Dimension(70, 42));

        Saldo2.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Saldo2.setText("Tipo de divisa");
        Saldo2.setPreferredSize(new java.awt.Dimension(70, 42));

        Saldo3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Saldo3.setText("¿Cuanto dinero ingresas?");
        Saldo3.setPreferredSize(new java.awt.Dimension(70, 42));

        Saldo4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Saldo4.setText("Lo entregado será este monto");
        Saldo4.setPreferredSize(new java.awt.Dimension(70, 42));

        MontoCambiado.setEditable(false);

        simular_cambio.setBackground(new java.awt.Color(76, 189, 228));
        simular_cambio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        simular_cambio.setText("Simular");
        simular_cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simular_cambioActionPerformed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(76, 189, 228));
        Volver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        Saldo5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        Saldo5.setText("<html>¿Máxima denominación en que deseas el dinero?<br> (La mayor parte posible bajo la misma selección)</html>");
        Saldo5.setToolTipText("");
        Saldo5.setPreferredSize(new java.awt.Dimension(70, 42));

        TipoDeDenom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1000", "2000", "5000", "10000", "20000", "50000", "100000" }));
        TipoDeDenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeDenomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setText("Se le restará una tarifa de servicio de:");

        tvcomision.setEditable(false);

        ConfirmarCambio1.setBackground(new java.awt.Color(76, 189, 228));
        ConfirmarCambio1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ConfirmarCambio1.setText("Cambiar");
        ConfirmarCambio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarCambio1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Saldo5, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmarCambio1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(tvcomision, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(MontoCambiado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(MontoACambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(simular_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(TipoDeDenom, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TipoDeDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoDeDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MontoACambiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simular_cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(tvcomision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MontoCambiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Saldo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TipoDeDenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Volver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ConfirmarCambio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDeDivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeDivisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeDivisaActionPerformed

    double entrega=0.0;
    
    private void simular_cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simular_cambioActionPerformed
        // TODO add your handling code here:
        String seleccion_divisa= (String) TipoDeDivisa.getSelectedItem();
        double monto_cambiar= Double.parseDouble(MontoACambiar.getText());
        double comision = 0.0, cambio;
        switch(seleccion_divisa){
            case "Dolar estadounidense":
               cambio = (monto_cambiar*4660)/1000;
               comision = (cambio%1)*1000;
               entrega = Math.floor(cambio)*1000;
               break;
            case "Real Brasileño":
               cambio = (monto_cambiar*922.47)/1000;
               comision = (cambio%1)*1000;
               entrega = (Math.floor(cambio)*1000);
               break;
            case "Libra Esterlina":
               cambio = (monto_cambiar*5808.7)/1000;
               comision = (cambio%1)*1000;
               entrega = (Math.floor(cambio)*1000);
               break;
            case "Euro":
               cambio = (monto_cambiar*5145.34)/1000;
               comision = (cambio%1)*1000;
               entrega = (Math.floor(cambio)*1000);
               break;
            case "Dirham":
               cambio = (monto_cambiar*1268.96)/1000;
               comision = (cambio%1)*1000;
               entrega = (Math.floor(cambio)*1000);
               break;
        }
        tvcomision.setText("COP "+String.format("%.1f",comision));
        MontoCambiado.setText("COP "+entrega);
        
    }//GEN-LAST:event_simular_cambioActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        Funcioprincipales principal = new Funcioprincipales();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverActionPerformed

    private void TipoDeDenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeDenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeDenomActionPerformed

    private void ConfirmarCambio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarCambio1ActionPerformed
        // TODO add your handling code here:
        String seleccion_den_combobox= (String) TipoDeDenom.getSelectedItem();
        int seleccion_denominacion = Integer.parseInt(seleccion_den_combobox);
        int contador_billetes = 0;
        while(entrega>=seleccion_denominacion){            
            contador_billetes++;
            entrega = entrega - seleccion_denominacion;
        }
        JOptionPane.showMessageDialog(null, "Se le entregaron "+contador_billetes+ " billetes de COP "+seleccion_denominacion+". Y un valor de COP "+entrega+" en denominación mixta");
        JOptionPane.showMessageDialog(null, "Gracias por utilizar nuestros servicios.");
        Funcioprincipales principal = new Funcioprincipales();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ConfirmarCambio1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambiarDivisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambiarDivisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambiarDivisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambiarDivisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambiarDivisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmarCambio1;
    private javax.swing.JTextField MontoACambiar;
    private javax.swing.JTextField MontoCambiado;
    private javax.swing.JLabel Saldo1;
    private javax.swing.JLabel Saldo2;
    private javax.swing.JLabel Saldo3;
    private javax.swing.JLabel Saldo4;
    private javax.swing.JLabel Saldo5;
    private javax.swing.JComboBox<String> TipoDeDenom;
    private javax.swing.JComboBox<String> TipoDeDivisa;
    private javax.swing.JButton Volver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton simular_cambio;
    private javax.swing.JTextField tvcomision;
    // End of variables declaration//GEN-END:variables
}
