/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import static proyecto.login.identificacion;

/**
 *
 * @author sxnti
 */
public class Funcioprincipales extends javax.swing.JFrame {

    Proyecto conexion = new Proyecto();
    Connection cn = conexion.getConexion();
    public static double saldo;
    
    public Funcioprincipales() {
        initComponents();
        addComponentListener(new ComponentAdapter() {
            public void componentShown(ComponentEvent e) {
                mostrar_saldo();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Saldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textview_saldo = new javax.swing.JTextField();
        Transferir = new javax.swing.JButton();
        CambioDivisa = new javax.swing.JButton();
        CambioDenominacion = new javax.swing.JButton();
        jbtn_ingresodinero = new javax.swing.JButton();
        jbtn_salir = new javax.swing.JButton();
        jbtn_cambiocont = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 111, 149));

        jPanel1.setBackground(new java.awt.Color(0, 111, 149));

        Saldo.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        Saldo.setText("Saldo");
        Saldo.setPreferredSize(new java.awt.Dimension(70, 42));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Captura_de_pantalla_2023-04-21_134746-removebg-preview2.png"))); // NOI18N

        textview_saldo.setEditable(false);
        textview_saldo.setBackground(new java.awt.Color(0, 111, 149));
        textview_saldo.setFont(new java.awt.Font("Lucida Sans", 3, 24)); // NOI18N
        textview_saldo.setBorder(null);
        textview_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textview_saldoActionPerformed(evt);
            }
        });

        Transferir.setBackground(new java.awt.Color(76, 189, 228));
        Transferir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Transferir.setText("Transferir");
        Transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferirActionPerformed(evt);
            }
        });

        CambioDivisa.setBackground(new java.awt.Color(76, 189, 228));
        CambioDivisa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CambioDivisa.setText("Cambio de divisas");
        CambioDivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioDivisaActionPerformed(evt);
            }
        });

        CambioDenominacion.setBackground(new java.awt.Color(76, 189, 228));
        CambioDenominacion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CambioDenominacion.setText("Cambio de denominación");
        CambioDenominacion.setToolTipText("");
        CambioDenominacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambioDenominacionActionPerformed(evt);
            }
        });

        jbtn_ingresodinero.setBackground(new java.awt.Color(76, 189, 228));
        jbtn_ingresodinero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtn_ingresodinero.setText("Ingresar/Retirar dinero");
        jbtn_ingresodinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_ingresodineroActionPerformed(evt);
            }
        });

        jbtn_salir.setBackground(new java.awt.Color(76, 189, 228));
        jbtn_salir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtn_salir.setText("Salir");
        jbtn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_salirActionPerformed(evt);
            }
        });

        jbtn_cambiocont.setBackground(new java.awt.Color(76, 189, 228));
        jbtn_cambiocont.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtn_cambiocont.setText("Cambiar contraseña");
        jbtn_cambiocont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_cambiocontActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Transferir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CambioDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CambioDenominacion)
                                    .addComponent(jbtn_ingresodinero))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtn_cambiocont)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtn_salir)
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 128, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textview_saldo)
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textview_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(52, 52, 52)
                .addComponent(Transferir)
                .addGap(18, 18, 18)
                .addComponent(CambioDivisa)
                .addGap(18, 18, 18)
                .addComponent(CambioDenominacion)
                .addGap(18, 18, 18)
                .addComponent(jbtn_ingresodinero)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_cambiocont)
                    .addComponent(jbtn_salir))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textview_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textview_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textview_saldoActionPerformed
    
    private void TransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferirActionPerformed
        // TODO add your handling code here:
        Transferirdinero1 transferir = new Transferirdinero1();
        transferir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TransferirActionPerformed

    private void CambioDivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioDivisaActionPerformed
        // TODO add your handling code here:
        CambiarDivisa cambiardivisa = new CambiarDivisa();
        cambiardivisa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CambioDivisaActionPerformed

    private void CambioDenominacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambioDenominacionActionPerformed
        // TODO add your handling code here:
        CambioDenominacion cambiardenominacion = new CambioDenominacion();
        cambiardenominacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CambioDenominacionActionPerformed

    private void jbtn_ingresodineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_ingresodineroActionPerformed
        // TODO add your handling code here:
        IngresoRetiro ingresoRetiro = new IngresoRetiro();
        ingresoRetiro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_ingresodineroActionPerformed

    private void jbtn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_salirActionPerformed
        // TODO add your handling code here:
        login login = new login();
        int resp = JOptionPane.showConfirmDialog(null, "¿Está seguro de cerrar su sesión?");
        if(resp==0){
        login.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_jbtn_salirActionPerformed

    private void jbtn_cambiocontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cambiocontActionPerformed
        // TODO add your handling code here:
        cambio_cont cambio_cont = new cambio_cont();
        cambio_cont.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_cambiocontActionPerformed
    
    public void mostrar_saldo(){
       try {
                PreparedStatement ps;
                ps = cn.prepareStatement("SELECT saldo FROM `usuarios` where identificacion='"+identificacion+"';");
                ResultSet rs = ps.executeQuery();
                rs.next();
                saldo = rs.getInt("saldo");
                textview_saldo.setText("Tienes: $"+saldo);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al recopilar datos", "Error de DB", JOptionPane.ERROR_MESSAGE);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcioprincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcioprincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcioprincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcioprincipales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcioprincipales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CambioDenominacion;
    private javax.swing.JButton CambioDivisa;
    private javax.swing.JLabel Saldo;
    private javax.swing.JButton Transferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_cambiocont;
    private javax.swing.JButton jbtn_ingresodinero;
    private javax.swing.JButton jbtn_salir;
    private javax.swing.JTextField textview_saldo;
    // End of variables declaration//GEN-END:variables
}
