package proyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import static proyecto.login.identificacion;

public class IngresoRetiro extends javax.swing.JFrame {

    public IngresoRetiro() {
        initComponents();
    }
    Proyecto conexion = new Proyecto();
    Connection cn = conexion.getConexion();
    
    double saldo = new Funcioprincipales().saldo;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dineroIngRet = new javax.swing.JTextField();
        aceptarIngRet = new javax.swing.JButton();
        VolverIngRet = new javax.swing.JButton();
        opcionIngRet = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 111, 149));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel1.setText("¿Qué deseas hacer?");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        jLabel2.setText("¿Cuánto dinero?");

        aceptarIngRet.setBackground(new java.awt.Color(76, 189, 228));
        aceptarIngRet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        aceptarIngRet.setText("Aceptar");
        aceptarIngRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarIngRetActionPerformed(evt);
            }
        });

        VolverIngRet.setBackground(new java.awt.Color(76, 189, 228));
        VolverIngRet.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        VolverIngRet.setText("Volver");
        VolverIngRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverIngRetActionPerformed(evt);
            }
        });

        opcionIngRet.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        opcionIngRet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingresar dinero", "Retirar dinero" }));
        opcionIngRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionIngRetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dineroIngRet, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(opcionIngRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(VolverIngRet, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aceptarIngRet, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(opcionIngRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(dineroIngRet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarIngRet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VolverIngRet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarIngRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarIngRetActionPerformed
        // TODO add your handling code here:
        String opcion= (String) opcionIngRet.getSelectedItem();
        double valor = Double.parseDouble(dineroIngRet.getText());
        if (opcion.equals("Ingresar dinero")) {
            aumentar_saldo(valor);
            JOptionPane.showMessageDialog(null, "Se han ingresado exitosamente COP "+valor, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            Funcioprincipales principal = new Funcioprincipales();
            principal.setVisible(true);
        } else { if(opcion.equals("Retirar dinero")){
                if(valor<=saldo){
                    disminuir_saldo(valor);
                    JOptionPane.showMessageDialog(null, "Se han retirado exitosamente COP "+valor, "Confirmación", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                    Funcioprincipales principal = new Funcioprincipales();
                    principal.setVisible(true);
                } else{
                    JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Error Form", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_aceptarIngRetActionPerformed

    private void VolverIngRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverIngRetActionPerformed
        // TODO add your handling code here:
        Funcioprincipales principal = new Funcioprincipales();
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverIngRetActionPerformed

    private void opcionIngRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionIngRetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcionIngRetActionPerformed

    public void aumentar_saldo(double monto){
            try {
                PreparedStatement ps = null;                
                //saldo=saldo+monto;
                ps = cn.prepareStatement("UPDATE usuarios SET saldo="+(saldo+monto)+" WHERE identificacion="+identificacion+";");
                ps.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al recopilar datos", "Error de DB", JOptionPane.ERROR_MESSAGE);
            }
    }
    
    public void disminuir_saldo(double monto){
            try {
                PreparedStatement ps = null;                
                //saldo=saldo-monto;
                ps = cn.prepareStatement("UPDATE usuarios SET saldo="+(saldo-monto)+" WHERE identificacion="+identificacion+";");
                ps.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error al recopilar datos", "Error de DB", JOptionPane.ERROR_MESSAGE);
            }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoRetiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverIngRet;
    private javax.swing.JButton aceptarIngRet;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dineroIngRet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> opcionIngRet;
    // End of variables declaration//GEN-END:variables
}
