/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sxnti
 */
public class Transferirdinero1 extends javax.swing.JFrame {

    double saldo = new Funcioprincipales().saldo;
    public Transferirdinero1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TipoDeCuenta = new javax.swing.JComboBox<>();
        Saldo1 = new javax.swing.JLabel();
        Saldo2 = new javax.swing.JLabel();
        Saldo3 = new javax.swing.JLabel();
        NumeroDeCuenta = new javax.swing.JTextField();
        Saldo4 = new javax.swing.JLabel();
        TipoDeDocumento = new javax.swing.JComboBox<>();
        Saldo5 = new javax.swing.JLabel();
        NumeroDeDocumento = new javax.swing.JTextField();
        ConfirmarTransf = new javax.swing.JButton();
        jbtn_transfvolver = new javax.swing.JButton();
        Saldo6 = new javax.swing.JLabel();
        valortransf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 111, 149));

        TipoDeCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ahorros", "Corriente" }));
        TipoDeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeCuentaActionPerformed(evt);
            }
        });

        Saldo1.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        Saldo1.setText("Transferencia");
        Saldo1.setPreferredSize(new java.awt.Dimension(70, 42));

        Saldo2.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Saldo2.setText("Tipo de cuenta");
        Saldo2.setPreferredSize(new java.awt.Dimension(70, 42));

        Saldo3.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Saldo3.setText("Numero de cuenta");
        Saldo3.setPreferredSize(new java.awt.Dimension(70, 42));

        Saldo4.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Saldo4.setText("Tipo de documento");
        Saldo4.setPreferredSize(new java.awt.Dimension(70, 42));

        TipoDeDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "C.E", "T.I", "NIT" }));
        TipoDeDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDeDocumentoActionPerformed(evt);
            }
        });

        Saldo5.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Saldo5.setText("Numero de documento");
        Saldo5.setPreferredSize(new java.awt.Dimension(70, 42));

        NumeroDeDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroDeDocumentoActionPerformed(evt);
            }
        });

        ConfirmarTransf.setBackground(new java.awt.Color(76, 189, 228));
        ConfirmarTransf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ConfirmarTransf.setText("Transferir");
        ConfirmarTransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmarTransfActionPerformed(evt);
            }
        });

        jbtn_transfvolver.setBackground(new java.awt.Color(76, 189, 228));
        jbtn_transfvolver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtn_transfvolver.setText("Volver");
        jbtn_transfvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_transfvolverActionPerformed(evt);
            }
        });

        Saldo6.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        Saldo6.setText("¿Cuánto dinero?");
        Saldo6.setPreferredSize(new java.awt.Dimension(70, 42));

        valortransf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valortransfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(TipoDeDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(TipoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Saldo5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Saldo6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valortransf, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(NumeroDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtn_transfvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmarTransf, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(NumeroDeDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Saldo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Saldo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Saldo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroDeCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Saldo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TipoDeDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Saldo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NumeroDeDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Saldo6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valortransf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_transfvolver)
                    .addComponent(ConfirmarTransf))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TipoDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeCuentaActionPerformed

    private void TipoDeDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDeDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDeDocumentoActionPerformed

    private void NumeroDeDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroDeDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroDeDocumentoActionPerformed

    private void jbtn_transfvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_transfvolverActionPerformed
        // TODO add your handling code here:
        Funcioprincipales inicio = new Funcioprincipales();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jbtn_transfvolverActionPerformed

    private void ConfirmarTransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmarTransfActionPerformed
        // TODO add your handling code here:
        String cuenta = NumeroDeCuenta.getText();
        String doc = NumeroDeDocumento.getText();
        int valor_transf = Integer.parseInt(valortransf.getText());
        if(cuenta.isEmpty() || doc.isEmpty()){
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos", "Error en formulario", JOptionPane.ERROR_MESSAGE);                
        } else {
            if(valor_transf<=saldo){
                int resp = JOptionPane.showConfirmDialog(null, "Confirma transferencia a la cuenta #"+cuenta+"?");
                if(resp==0){
                    IngresoRetiro IngRet = new IngresoRetiro();
                    IngRet.disminuir_saldo(valor_transf);
                    JOptionPane.showMessageDialog(null, "Serás redirigido a PSE pasarela de pagos");
                    this.setVisible(false);                    
                    Funcioprincipales inicio = new Funcioprincipales();
                    inicio.setVisible(true);
                    try {
                        Desktop.getDesktop().browse(new URI("https://registro.pse.com.co/PSEUserRegister/"));
                    } catch (URISyntaxException ex) {
                        Logger.getLogger(Transferirdinero1.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Transferirdinero1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } else{
                JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Error Form", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ConfirmarTransfActionPerformed

    private void valortransfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valortransfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valortransfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferirdinero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferirdinero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferirdinero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferirdinero1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferirdinero1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmarTransf;
    private javax.swing.JTextField NumeroDeCuenta;
    private javax.swing.JTextField NumeroDeDocumento;
    private javax.swing.JLabel Saldo1;
    private javax.swing.JLabel Saldo2;
    private javax.swing.JLabel Saldo3;
    private javax.swing.JLabel Saldo4;
    private javax.swing.JLabel Saldo5;
    private javax.swing.JLabel Saldo6;
    private javax.swing.JComboBox<String> TipoDeCuenta;
    private javax.swing.JComboBox<String> TipoDeDocumento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtn_transfvolver;
    private javax.swing.JTextField valortransf;
    // End of variables declaration//GEN-END:variables
}
